### ISSUE TITLE
Dead links to github.io

### ISSUE THREAD

**Issue by slashme** [patrickfuller/blender-chemicals#2]
I just clicked on [your blog link](http://www.patrickfuller.github.io/molecules-from-smiles-molfiles-in-blender/) in README.md, and got a 404 error page.

**Comment by AdamK117** [comment]
Just incase you need it still. I believe the actual link is: https://patrickfuller.github.io/molecules-from-smiles-molfiles-in-blender/

**Comment by slashme** [comment]
Although it's probably easier to fix by hand, I've created a pull request to fix the link :-D
