### ISSUE TITLE
can not run from anoconda

### ISSUE THREAD

**Issue by jacksparrowFF2** [patrickfuller/blender-chemicals#7]
blender-chemicals c1ccccc1

 Open Babel Warning  in OpenBabel::OBGlobalDataBase::Init
  Cannot open aromatic.txt defaulting to compiled data.

Open Babel Warning  in OpenBabel::OBGlobalDataBase::Init
  Cannot open atomtyp.txt defaulting to compiled data.

 Open Babel Warning  in OpenBabel::OBGlobalDataBase::Init
  Cannot open element.txt defaulting to compiled data.

 Open Babel Warning  in OpenBabel::OBGlobalDataBase::Init
  Cannot open phmodel.txt defaulting to compiled data.

 Open Babel Error  in OpenBabel::OBBuilder::LoadFragments
  Cannot open fragments.txt

 Open Babel Error  in OpenBabel::OBForceFieldMMFF94::ParseParamFile
  Cannot open parameter file

 Open Babel Warning  in OpenBabel::OBGlobalDataBase::Init
  Cannot open element.txt defaulting to compiled data.

HI! 
I followed the instruction to install the software mentioned in the ReadMe, but when  I try to run this program, it will show this on my computer, how can I solve this problem?

os : win10
blender Version: 2.81

**Comment by patrickfuller** [comment]
This looks like a problem with installing open babel so that would be a better place to look. With conda, I install with `conda install -c openbabel openbabel`.

Hope this helps!
