### ISSUE TITLE
Hitting a problem at line with the line:     args = sys.argv[sys.argv.index('--') + 1:]

### ISSUE THREAD

**Issue by Davys224** [patrickfuller/blender-chemicals#9]
Hello,

I've pasted "draw.py" in the scripting panel and hard-coded the path...everything seems to run well until it gets to the line I put in the title (and below).
Using Blender 2.9

Obviously, I don't get outputs!
To check my hardcoded PATH, I went into Anaconda and ran the lines and asked it to PRINT the JSON in the console. It performed perfectly, so I'm fairly confident of this part.

I wish I could give you the output in the console, but I have none, I'm using Blender portable 2.9...seems to be more stable on my laptop than the installed one.

Thanks in advance!

Bit of code so it gets clearer:

#Hard-coding my location:
PATH = 'C:/Users/UserName/Documents/Molecules_jsons/'    #Obviously /UserName/ has the right name, but I removed it here
with open(os.path.join(PATH, 'caffeine.json')) as in_file:     #Testing "draw.py" using caffeine.
    atom_data = json.load(in_file)

#The part that's giving me headaches

if __name__ == '__main__':
    """Uses Blender's limited argv interface to pass args from main script."""
    args = sys.argv[sys.argv.index('--') + 1:]    #This line stops script in Blender, I've not changed anything from "draw.py" 
    show_bonds, join = True, True
    if '--space-filling' in args:
        show_bonds = False
        args.remove('--space-filling')
    if '--no-join' in args:
        join = False
        args.remove('--no-join')

    try:
        with open(args[0]) as in_file:
            molecule = json.load(in_file)
    except IOError:
        molecule = json.loads(args[0])

    draw_molecule(molecule, show_bonds=show_bonds, join=join)

UPDATE:
I got Blender to show me the console (Finally, why a separate window!):
Traceback (most recent call last):
  File "\draw_molecules.py", line 159, in <module>
ValueError: '--' is not in list
Error: Python script failed, check the message in the system console

**Comment by patrickfuller** [comment]
Hi @Davys224,

I threw together and tested a quick example to show you how to get it working. 
[Chemicals Example.zip](https://github.com/patrickfuller/blender-chemicals/files/6178127/Chemicals.Example.zip)

Blender's changed how they handle python between operating systems in small subtle ways so it can take a few attempts to get right. This is working on Blender 2.83 on macOS Big Sur.

Hope it helps!

**Comment by Davys224** [comment]
Hi,

Thanks, for the files "Chemical Example.zip" the routine goes through.
However, I can't get ANY JSON (PubChem, CDJSON) aside from your molecule to be drawn well...Where do you get JSON? I tried to convert from molview (which yields a mol file that OpenBabel can transform)...the results are either a big black cylinder or a sphere.OpenBabel does not save as just a *.json, but as *.*json as they're multiple .json file formats it seems.

The "molecule.json" file in the archive you sent me has this as architecture:

{
    "atoms": [
        { "element": "C", "location": [ -0.76197, 1.16831, -0.00162 ] },
        { "element": "C", "location": [ 0.6308, 1.24404, -0.00065 ] },
        { "element": "C", "location": [ 1.39277, 0.07573, 0.00097 ] },
        { "element": "C", "location": [ 0.76197, -1.16831, 0.00162 ] },
        { "element": "C", "location": [ -0.6308, -1.24404, 0.00065 ] },
        { "element": "C", "location": [ -1.39277, -0.07573, -0.00098 ] },
        { "element": "H", "location": [ -1.35563, 2.07855, -0.00289 ] },
        { "element": "H", "location": [ 1.12226, 2.21329, -0.00115 ] },
        { "element": "H", "location": [ 2.47789, 0.13474, 0.00173 ] },
        { "element": "H", "location": [ 1.35563, -2.07855, 0.00289 ] },
        { "element": "H", "location": [ -1.12226, -2.21329, 0.00115 ] },
        { "element": "H", "location": [ -2.47789, -0.13474, -0.00174 ] }
    ],
    "bonds": [
        { "atoms": [ 0, 1 ], "order": 2 },
        { "atoms": [ 1, 2 ], "order": 1 },
        { "atoms": [ 2, 3 ], "order": 2 },
        { "atoms": [ 3, 4 ], "order": 1 },
        { "atoms": [ 4, 5 ], "order": 2 },
        { "atoms": [ 0, 5 ], "order": 1 },
        { "atoms": [ 0, 6 ], "order": 1 },
        { "atoms": [ 1, 7 ], "order": 1 },
        { "atoms": [ 2, 8 ], "order": 1 },
        { "atoms": [ 3, 9 ], "order": 1 },
        { "atoms": [ 4, 10 ], "order": 1 },
        { "atoms": [ 5, 11 ], "order": 1 }
    ]
}


But it is not like ANY JSON that I can find...
OpenBabel yields JSON as either of .pcjson or .cdjson and the files' architecture are not the same from "molecule.json" which you gave me in the zip archive.
Moreover, manually downloading a json from PubChem also doesn't yield a json file with the architecture you sent me!
I tried with compound benzene which is "molecule.json" if I do not miss my guess and it doesn't work AT ALL.

Your routine definitely doesn't like this...If I follow the code, the in the .blend file you sent me, it doesn't read the OpenBabel files the way they are formatted!! Nor does it read the manually downloaded .json from PubChem. Unless your system is sending special instructions to OpenBabel for how to make the JSON, I can't see it working well.

I honestly think that your routine is great, however, your "molecule.json" file is definitely not the same architecture as the one that OpenBabel can make or that PubChem gives on its website.
I'm thinking that json formatting has changed as your file "molecule.json" looks an awful lot like an .xyz file. It's possible they changed the architecture of a json file.

Anyway, I guess I'll be going back to using the other method I've been using while teaching even if it's longer...I liked your method because it color coded in one shot...I'd be willing to troubleshoot with bigger and bigger molecule later on, but it won't work for now.

I also tried it with "Chlorophyll a" and it yields the exact same fail result.

Sincerely,
Davys224

**Comment by Davys224** [comment]
> Hi @Davys224,
> 
> I threw together and tested a quick example to show you how to get it working. Unzip all to the same directory and then open the blender file. Clicking the "play" button above the script should draw a benzene molecule.
> [Chemicals Example.zip](https://github.com/patrickfuller/blender-chemicals/files/6178127/Chemicals.Example.zip)
> 
> Blender's changed how they handle python between operating systems in small subtle ways so it can take a few attempts to get right. This is working on Blender 2.83 on macOS Big Sur.
> 
> Hope it helps!

Thanks, it does!!!
